server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:file:./data/orderdb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
url:
  user-service: http://localhost:8083/api/users
  product-service: http://localhost:8081/api/products